server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5342/
    username: admin
    password: Password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
